[tools]
go = "1.25.1"
hugo = "0.150.0"
ruby = { version = "4.0.0", postinstall = "gem install ruby-lsp rubocop" }
node = { version = "24.3.0", postinstall = "npm install -g typescript-language-server typescript @github/copilot-language-server" }
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]

