[tools]
go = "1.25.1"
hugo = "0.150.0"
ruby = "3.4.4"
node = "24.3.0"

gh = "2.79.0"
jq = "1.8.1"
fzf = "0.65.2"
colima = "0.8.4"
lima = "1.2.1"
yazi = "25.3.2"
ripgrep = "14.1.1"
peco = "0.5.11"
eza = "0.23.3"
delta = "0.18.2"
lazygit = "0.55.0"
neovim = "0.11.4"
lua-language-server = "3.15.0"
stylua = "2.2.0"
terraform-ls = "0.37.0"
tflint = "0.59.1"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]

