[[plugins]] # TOML形式のシンタックスハイライトを有効
repo = 'cespare/vim-toml'

[[plugins]] # :helpを日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]] # カラースキーマ
repo = 'EdenEast/nightfox.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/colorscheme.vim
'''

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.config/nvim/plugins/lightline.vim
'''

[[plugins]] # filer
repo = 'lambdalisue/fern.vim'
hook_add = '''
  source ~/.config/nvim/plugins/fern.vim
'''

[[plugins]] # file preview
repo = 'yuki-yano/fern-preview.vim'
hook_add = '''
  source ~/.config/nvim/plugins/fern-preview.vim
'''

[[plugins]] # ファイルツリーにgitの差分を表示する
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]] # font & file icon
repo = 'lambdalisue/nerdfont.vim'

[[plugins]] # filerのアイコン表示
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  source ~/.config/nvim/plugins/fern-renderer-nerdfont.vim
'''

[[plugins]] # ファイラーのアイコンをカラー表示
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  source ~/.config/nvim/plugins/glyph-pallette.vim
'''

[[plugins]] # ターミナル拡張
repo ='Shougo/deol.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/deol.vim
'''

[[plugins]] # Git操作
repo = 'lambdalisue/gina.vim'
hook_add = '''
  source ~/.config/nvim/plugins/gina.vim
'''

[[plugins]] # Gitの変更表示
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/plugins/vim-gitgutter.vim
'''

[[plugins]] # コンフリクトマーカー
repo = 'rhysd/conflict-marker.vim'
hook_add = '''
  source ~/.config/nvim/plugins/conflict-marker.vim
'''

[[plugins]] # lazygit
repo = 'kdheepak/lazygit.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/lazygit.vim
'''

[[plugins]] # コメントアウト用 nvim-ts-context-commentstringと組み合わせる
repo = 'numToStr/Comment.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/comment.lua
'''

[[plugins]] # yank範囲をハイライトする
repo = 'machakann/vim-highlightedyank'
hook_add = '''
  source ~/.config/nvim/plugins/vim-highlightedyank.vim
'''

[[plugins]] # windowのリサイズ
repo = 'simeji/winresizer'

[[plugins]] # 対応する()のカラーリング
repo = 'luochen1990/rainbow'
hook_add = '''
  source ~/.config/nvim/plugins/rainbow.vim
'''

[[plugins]] # 翻訳
repo = 'skanehira/translate.vim'
hook_add = '''
  source ~/.config/nvim/plugins/translate.vim
'''

[[plugins]] # チートシート
repo = 'reireias/vim-cheatsheet'
hook_add = '''
  source ~/.config/nvim/plugins/cheatsheet.vim
'''

[[plugins]] # スペルチェック
repo = 'kamykn/spelunker.vim'

[[plugins]] # スペルチェック拡張のneovim対応
repo = 'kamykn/popup-menu.nvim'

[[plugins]] # bufferlineにアイコンを表示
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]] # buffer lineにbufferを表示
repo = 'romgrk/barbar.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/barbar.vim
'''

[[plugins]] # / or ? 検索のジャンプ拡張
repo = 'hrsh7th/vim-searchx'
hook_add = '''
  source ~/.config/nvim/plugins/searchx.vim
'''

[[plugins]] # シンタックスハイライトを有効化
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = '''
  source ~/.config/nvim/plugins/treesitter.vim
'''

[[plugins]] # jsx,tsxコメントアウト
repo = 'JoosepAlviste/nvim-ts-context-commentstring'

[[plugins]] # indentline
repo = 'lukas-reineke/indent-blankline.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/indent-blackline.lua
'''

[[plugins]] # 対応する括弧などを補完
repo = 'cohama/lexima.vim'

[[plugins]] # js&ts&jsx&tsx formatter linter
repo = 'dense-analysis/ale'
hook_add = '''
let g:ale_fixers = {
\   'typescript': ['prettier'],
\   'typescriptreact': ['prettier'],
\   'javascript': ['prettier'],
\   'javascriptreact': ['prettier'],
\   'css': ['prettier'],
\   'go': ['gofmt'],
\   'markdown': ['prettier'],
\   'php': ['php_cs_fixer'],
\}

let g:ale_sign_error = '>>'
let g:ale_sign_warning = '--'
let g:ale_echo_msg_format = '[%linter%] %code: %%s'
let g:ale_statusline_format = ['E%d', 'W%d', 'OK']

let g:ale_fix_on_save = 1
let g:ale_php_php_cs_fixer_executable = '/usr/local/bin/php-cs-fixer'
let g:ale_javascript_prettier_use_local_config = 1
let g:ale_typescript_prettier_use_local_config = 1
let g:ale_javascript_prettier_options = '--printWidth 100 --tabWidth 2 --single-quote --jsxSingleQuote true --trailing-comma es5 --bracketSpacing true --jsxBracketSameLine --semi true --errorParens avoid --endOfLine crlf'
let g:ale_typescript_prettier_options = '--printWidth 100 --tabWidth 2 --single-quote --jsxSingleQuote true --trailing-comma es5 --bracketSpacing true --jsxBracketSameLine --semi true --errorParens avoid --endOfLine crlf'
'''
