#################################################################################################
# 見た目系プラグイン
#################################################################################################
[[plugins]] # シンタックスハイライトを有効化
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = '''
  source ~/.config/nvim/plugins/treesitter.lua
'''

[[plugins]] # カラースキーマ
repo = 'EdenEast/nightfox.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/colorscheme.lua
'''

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.config/nvim/plugins/lightline.lua
'''

[[plugins]] # ファイルツリーにgitの差分を表示する
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]] # font & file icon
repo = 'lambdalisue/nerdfont.vim'

[[plugins]] # filerのアイコン表示
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  source ~/.config/nvim/plugins/fern.lua
'''

[[plugins]] # ファイラーのアイコンをカラー表示
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  source ~/.config/nvim/plugins/glyph-pallette.lua
'''

[[plugins]] # 対応する()のカラーリング
repo = 'luochen1990/rainbow'
hook_add = '''
  source ~/.config/nvim/plugins/rainbow.lua
'''

[[plugins]] # bufferlineにアイコンを表示
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]] # buffer lineにbufferを表示
repo = 'romgrk/barbar.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/barbar.lua
'''

[[plugins]] # indentline
repo = 'lukas-reineke/indent-blankline.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/indent-blackline.lua
'''

[[plugins]] # TOML形式のシンタックスハイライトを有効
repo = 'cespare/vim-toml'

#################################################################################################
# 翻訳系プラグイン
#################################################################################################
[[plugins]] # :helpを日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # 翻訳
repo = 'skanehira/translate.vim'
hook_add = '''
  source ~/.config/nvim/plugins/translate.lua
'''

#################################################################################################
# 開発体験UP系プラグイン
#################################################################################################
[[plugins]] # Gitの変更表示
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/plugins/vim-gitgutter.lua
'''

[[plugins]] # コンフリクトマーカー
repo = 'rhysd/conflict-marker.vim'
hook_add = '''
  source ~/.config/nvim/plugins/conflict-marker.lua
'''

[[plugins]] # lazygit(git ui)
repo = 'kdheepak/lazygit.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/lazygit.lua
'''

[[plugins]] # git blame(vscodeのGitlensのようなもの)
repo = 'APZelos/blamer.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/blamer.lua
'''

[[plugins]] # コメントアウト用 nvim-ts-context-commentstringと組み合わせる
repo = 'numToStr/Comment.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/comment.lua
'''

[[plugins]] # jsx,tsxコメントアウト
repo = 'JoosepAlviste/nvim-ts-context-commentstring'

[[plugins]] # debug adapter protocol
repo = 'mfussenegger/nvim-dap'
hook_add = '''
  source ~/.config/nvim/plugins/nvim-dap.lua
'''

[[plugins]] # debug ui
repo = 'rcarriga/nvim-dap-ui'
hook_add = '''
  source ~/.config/nvim/plugins/nvim-dap-ui.lua
'''

[[plugins]] # debug for golang
repo = 'leoluz/nvim-dap-go'
hook_add = '''
  source ~/.config/nvim/plugins/nvim-dap-go.lua
'''

#################################################################################################
# 操作性UP系プラグイン
#################################################################################################
[[plugins]] # filer
repo = 'lambdalisue/fern.vim'
hook_add = '''
  source ~/.config/nvim/plugins/fern.lua
'''

[[plugins]] # file preview
repo = 'yuki-yano/fern-preview.vim'
hook_add = '''
  source ~/.config/nvim/plugins/fern.lua
'''

[[plugins]] # ターミナル拡張
repo ='Shougo/deol.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/deol.lua
'''

[[plugins]] # yank範囲をハイライトする
repo = 'machakann/vim-highlightedyank'
hook_add = '''
  source ~/.config/nvim/plugins/vim-highlightedyank.lua
'''

[[plugins]] # windowのリサイズ
repo = 'simeji/winresizer'

[[plugins]] # / or ? 検索のジャンプ拡張
repo = 'hrsh7th/vim-searchx'
hook_add = '''
  source ~/.config/nvim/plugins/searchx.lua
'''

#################################################################################################
# 補完、リント系プラグイン
#################################################################################################
[[plugins]] # スペルチェック
repo = 'kamykn/spelunker.vim'

[[plugins]] # スペルチェック拡張のneovim対応
repo = 'kamykn/popup-menu.nvim'

[[plugins]] # 対応する括弧などを補完
repo = 'cohama/lexima.vim'

[[plugins]] # js&ts&jsx&tsx formatter linter
repo = 'dense-analysis/ale'
hook_add = '''
  source ~/.config/nvim/plugins/ale.lua
'''

#################################################################################################
# その他（依存関係など）
#################################################################################################
[[plugins]] # チートシート
repo = 'reireias/vim-cheatsheet'
hook_add = '''
  source ~/.config/nvim/plugins/cheatsheet.vim
'''

[[plugins]] # Denoでプラグインを作るエコシステム
repo = 'vim-denops/denops.vim'


#################################################################################################
# LSPプラグイン
#################################################################################################
[[plugins]] # Neovim Builtin LSPが提供する構文を引っ張ってくる
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]] # 入力補完プラグイン
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
depends = ['denops.vim']
hook_add = '''
  source ~/.config/nvim/plugins/ddc.vim
'''

[[plugins]] # 補完候補
repo = 'Shougo/pum.vim'

[[plugins]] # 補完候補UI
repo = 'Shougo/ddc-ui-native'

[[plugins]] # 補完(ddc-matcher_head, ddc-sorter_rank, ddc-converter_remove_overlapとほぼ同じ機能)
repo = 'tani/ddc-fuzzy'

[[plugins]] # 行の周辺の単語を候補として抽出
repo = 'Shougo/ddc-source-around'

[[plugins]] # スニペット
repo = 'hrsh7th/vim-vsnip'
on_event = 'InsertEnter'
depends = ['vim-vsnip-integ', 'friendly-snippets']
hook_add = '''
imap <expr> <C-j> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-j>'
smap <expr> <C-j> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-j>'
imap <expr> <Tab> vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : '<Tab>'
smap <expr> <Tab> vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : '<Tab>'
imap <expr> <S-Tab> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<S-Tab>'
smap <expr> <S-Tab> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<S-Tab>'
let g:vsnip_filetypes = {}
'''

[[plugins]] # スニペット
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]] # スニペット
repo = 'rafamadriz/friendly-snippets'

#################################################################################################
# Language protocol server
###############################################################################################

[[plugins]] # Nvim LSPの設定
repo = 'neovim/nvim-lspconfig'

[[plugins]] # LSP, DAP, Linter, Formatter
repo = 'williamboman/mason.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/mason.lua
'''

[[plugins]] # LSP, DAP, Linter, Formatterの管理
repo = 'williamboman/mason-lspconfig.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/mason-lspconfig.lua
'''
