-- -----------------------------------
-- Loading neovim plugin settings
-- -----------------------------------
require('configs/barbar')
require('configs/cheatsheet')
require('configs/colorscheme')
require('configs/comment')
require('configs/conflict-marker')
require('configs/ddc')
require('configs/deol')
require('configs/fern')
require('configs/glyph-pallette')
require('configs/indent-blankline')
require('configs/lazygit')
require('configs/nvim-dap-go')
require('configs/nvim-dap-ruby')
require('configs/nvim-dap-ui')
require('configs/nvim-dap')
require('configs/rainbow')
require('configs/searchx')
require('configs/translate')
require('configs/treesitter')
require('configs/vim-gitgutter')
require('configs/vim-highlightedyank')
require('configs/nvim-lspconfig')
require('configs/null-ls')
require('configs/prettier')
require('configs/alpha')
require('configs/vim-illuminate')
require('configs/todo-comments')
require('configs/gitsigns')
require('configs/lualine')
require('configs/neogit')
require('configs/telescope')
require('configs/nvim-ts-autotag')
require('configs/noice')
