prSections:
- title: My Pull Requests
  filters: is:open author:@me
  layout:
    author:
      hidden: true
- title: Needs My Review
  filters: is:open review-requested:@me
- title: Involved
  filters: is:open involves:@me -author:@me
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: false
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
        hidden: false
      repo:
        width: 15
        hidden: false
      title:
        width: 15
        hidden: false
      author:
        width: 15
        hidden: false
      reviewStatus:
        width: 5
        hidden: false
      state:
        width: 5
        hidden: false
      ci:
        width: 5
        hidden: false
      lines:
        width: 16
      assignees:
        width: 15
        hidden: true
      base:
        width: 5
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
repoPaths:
theme:
  ui:
    table:
      showSeparator: true
    colors:
      text:
        primary: '#E2E1ED'
        secondary: '#666CA6'
        inverted: '#242347'
        faint: '#3E4057'
        warning: '#F23D5C'
        success: '#3DF294'
      background:
        selected: '#39386B'
      border:
        primary: '#383B5B'
        secondary: '#39386B'
        faint: '#2B2B40'
pager:
  diff: 'delta'

